var avengersVsXmenCardData = [
  {
    id: 1,
    dieId: 1,
    name:        "Beast",
    subtitle:    "Big Boy Blue",
    cost:        2,
    type:        "Mask",
    affiliation: "X-Men",
    rarity:      "Starter",
    ability:     "Beast gets a +1A and +1D (until the end of the turn) when he blocks.",
    "* ability": "He gets +2A and +2D instead.",
    "** ability":  "",
    global:      "",
    dieLimit:   4
  },
  {
    id: 2,
    dieId: 1,
    name:        "Beast",
    subtitle:    "Genetic Expert",
    cost:        2,
    type:        "Mask",
    affiliation: "X-Men",
    rarity:      "Starter",
    ability:     "If Beast is knocked out while blocking, you gain 1 life.",
    "* ability": "Your opponent also takes 2 damage.",
    "** ability":  "",
    global:      "",
    dieLimit:   4
  },
  {
    id: 3,
    dieId: 1,
    name:        "Beast",
    subtitle:    "Mutate #666",
    cost:        2,
    type:        "Mask",
    affiliation: "X-Men",
    rarity:      "Starter",
    ability:     "When Beast blocks, draw one die and place it in your prep area.",
    "* ability": "Instead draw 2 dice; place one in your prep area and the other in your used pile.",
    "** ability":  "",
    global:      "",
    dieLimit:   4
  },
  {
    id: 4,
    dieId: 2,
    name:        "Captain America",
    subtitle:    "American Hero",
    cost:        4,
    type:        "Shield",
    affiliation: "Avengers",
    rarity:      "Starter",
    ability:     "When fielded, you may roll a Sidekick die from your used pile (you cannot select a die that paid to field this one; place the die in your reserve pool).",
    "* ability": "",
    "** ability":  "",
    global:      "",
    dieLimit:   4
  },
  {
    id: 5,
    dieId: 2,
    name:        "Captain America",
    subtitle:    "Natural Leader",
    cost:        4,
    type:        "Shield",
    affiliation: "Avengers",
    rarity:      "Starter",
    ability:     "While Captain America is active, your Sidekick characters get +1A and +1D (no matter how many Captain America dice you have fielded).",
    "* ability": "",
    "** ability":  "",
    global:      "",
    dieLimit:   4
  },
  {
    id: 6,
    dieId: 2,
    name:        "Captain America",
    subtitle:    "Star-Spangled Avenger",
    cost:        5,
    type:        "Shield",
    affiliation: "Avengers",
    rarity:      "Starter",
    ability:     "When fielded, knock out each of your opponent's Sidekick characters.  Gain 1 life for each Sidekick knocked out this way.",
    "* ability": "",
    "** ability":  "",
    global:      "",
    dieLimit:   4
  },
  {
    id: 7,
    dieId: 3,
    name:        "Hulk",
    subtitle:    "Anger Issue",
    cost:        7,
    type:        "Fist",
    affiliation: "Avengers",
    rarity:      "Starter",
    ability:     "While Hulk is active, when either you or Hulk take damage, Hulk gets +2A and +2D (until the end of the turn).",
    "* ability": "Hulk gets +3A and +3D instead.",
    "** ability":  "",
    global:      "",
    dieLimit:   4
  },
  {
    id: 8,
    dieId: 3,
    name:        "Hulk",
    subtitle:    "Annihilator",
    cost:        6,
    type:        "Fist",
    affiliation: "Avengers",
    rarity:      "Starter",
    ability:     "While Hulk is active, when either you or Hulk take damage, move all Hulk dice from your used pile to your prep area.",
    "* ability": "",
    "** ability":  "",
    global:      "",
    dieLimit:   4
  },
  {
    id: 9,
    dieId: 3,
    name:        "Hulk",
    subtitle:    "Jade Giant",
    cost:        6,
    type:        "Fist",
    affiliation: "Avengers",
    rarity:      "Starter",
    ability:     "While Hulk is active, when either you or Hulk take damage, knock out one of your opponent's level 1 characters.",
    "* ability": "Instead knock out one opposing character of any level.",
    "** ability":  "",
    global:      "",
    dieLimit:   4
  },
  {
    id: 10,
    dieId: 4,
    name:        "Human Torch",
    subtitle:    "Flame On!",
    cost:        4,
    type:        "Bolt",
    affiliation: "Fantastic Four",
    rarity:      "Starter",
    ability:     "While Human Torch is active, he deals 1 damage to a character or player each time you field a character (not 1 damage per die).",
    "* ability": "",
    "** ability":  "",
    global:      "Pay [1 Bolt] when you deal damage with an action die or global ability to deal one extra damage to one target.",
    dieLimit:   4
  },
  {
    id: 11,
    dieId: 4,
    name:        "Human Torch",
    subtitle:    "Matchstick",
    cost:        3,
    type:        "Bolt",
    affiliation: "Fantastic Four",
    rarity:      "Starter",
    ability:     "While Human Torch is active, each time you field a character, you may roll one Human Torch from your used pile (not one that paid to field the die).  If you roll a character side, place it in your reserve pool; otherwise place it in your used pile.",
    "* ability": "",
    "** ability":  "",
    global:      "",
    dieLimit:   4
  },
  {
    id: 12,
    dieId: 4,
    name:        "Human Torch",
    subtitle:    "Playing with Fire",
    cost:        2,
    type:        "Bolt",
    affiliation: "Fantastic Four",
    rarity:      "Starter",
    ability:     "The first time you field a character each turn, each Human Torch already in the field gets +1A and +1D (until the end of the turn).",
    "* ability": "",
    "** ability":  "",
    global:      "",
    dieLimit:   4
  },
  {
    id: 13,
    dieId: 5,
    name:        "Iron Man",
    subtitle:    "Inventor",
    cost:        4,
    type:        "Shield",
    affiliation: "Avengers",
    rarity:      "Starter",
    ability:     "Each time Iron Man takes damage, reduce the damage he takes by 1.",
    "* ability": "Reduce the damage by 2 instead.",
    "** ability":  "",
    global:      "Pay [1 Shield] to redirect 1 damage from you to one of your characters.",
    dieLimit:   4
  },
  {
    id: 14,
    dieId: 5,
    name:        "Iron Man",
    subtitle:    "Philanthropist",
    cost:        5,
    type:        "Shield",
    affiliation: "Avengers",
    rarity:      "Starter",
    ability:     "Each time Iron Man takes damage, you gain 1 life.",
    "* ability": "Gain 2 life instead.",
    "** ability":  "",
    global:        "",
    dieLimit:   4
  },
  {
    id: 15,
    dieId: 5,
    name:        "Iron Man",
    subtitle:    "Playboy",
    cost:        4,
    type:        "Shield",
    affiliation: "Avengers",
    rarity:      "Starter",
    ability:     "Each time Iron Man takes damage in the attack step, he deals 3 damage to one opposing character that is attacking or blocking.",
    "* ability": "",
    "** ability":  "",
    global:      "",
    dieLimit:   4
  },
  {
    id: 16,
    dieId: 6,
    name:        "Spider-Man",
    subtitle:    "\"Tiger\"",
    cost:        4,
    type:        "Fist",
    affiliation: "None",
    rarity:      "Starter",
    ability:     "You may pay [1 Fist] to prevent Spider-Man from being affected by an ability or game effect (other than damage from a character engaged with him).",
    "* ability": "",
    "** ability":  "",
    global:      "",
    dieLimit:   4
  },
  {
    id: 17,
    dieId: 6,
    name:        "Spider-Man",
    subtitle:    "Webhead",
    cost:        4,
    type:        "Fist",
    affiliation: "None",
    rarity:      "Starter",
    ability:     "When Spider-Man assigns to attack, you may pay [1 Fist] to give him +4D (you can only do this once per turn per die).",
    "* ability": "",
    "** ability":  "",
    global:      "",
    dieLimit:   4
  },
  {
    id: 18,
    dieId: 6,
    name:        "Spider-Man",
    subtitle:    "Webslinger",
    cost:        5,
    type:        "Fist",
    affiliation: "None",
    rarity:      "Starter",
    ability:     "When Spider-Man assigns to attack, you may pay [1 Fist] to force every opposing character to block him if able.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 19,
    dieId: 7,
    name:        "Storm",
    subtitle:    "African Priestess",
    cost:        3,
    type:        "Mask",
    affiliation: "X-Men",
    rarity:      "Starter",
    ability:     "When fielded, reroll a target opposing character.  If the result is not a character, place that die in your opponent's used pile.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 20,
    dieId: 7,
    name:        "Storm",
    subtitle:    "Goddess of the Plains",
    cost:        4,
    type:        "Mask",
    affiliation: "X-Men",
    rarity:      "Starter",
    ability:     "When Storm attacks, reroll each of your opponent's characters. Place any die that does not result in a character in your opponent's prep area.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 21,
    dieId: 7,
    name:        "Storm",
    subtitle:    "Ro",
    cost:        2,
    type:        "Mask",
    affiliation: "X-Men",
    rarity:      "Starter",
    ability:     "After blockers are assigned, reroll all characters engaged with Storm.  Place each such die that does not show a character in your opponent's prep area.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 22,
    dieId: 8,
    name:        "Thor",
    subtitle:    "Legendary Warrior",
    cost:        6,
    type:        "Bolt",
    affiliation: "Avengers",
    rarity:      "Starter",
    ability:     "When Thor damages your opponent, knock out an opposing [Fist] character.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 23,
    dieId: 8,
    name:        "Thor",
    subtitle:    "Lord of Asgard",
    cost:        6,
    type:        "Bolt",
    affiliation: "Avengers",
    rarity:      "Starter",
    ability:     "Thor can't be blocked by [Fist] characters.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 24,
    dieId: 8,
    name:        "Thor",
    subtitle:    "Odinson",
    cost:        6,
    type:        "Bolt",
    affiliation: "Avengers",
    rarity:      "Starter",
    ability:     "When fielded, capture all opposing [Fist] characters (return them at the end of the turn).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 25,
    dieId: 9,
    name:        "Basic Action Card",
    subtitle:    "Distraction",
    cost:        4,
    type:        "Generic",
    affiliation: "None",
    rarity:      "Starter",
    ability:     "Your opponent targets two of his or her characters. Those characters cannot block (this turn).",
    "* ability": "",
    "** ability":  "",
    global:       "Pay [1 Mask] to remove one attacker from the attack zone to the field.",
    dieLimit:   3
  },
  {
    id: 26,
    dieId: 9,
    name:        "Basic Action Card",
    subtitle:    "Focus Power",
    cost:        4,
    type:        "Generic",
    affiliation: "None",
    rarity:      "Starter",
    ability:     "Spin one target character up or down one level.",
    "* ability": "Spin a second target character up or down one level.",
    "** ability":  "Spin a second target character up or down one level.",
    global:       "",
    dieLimit:   3
  },
  {
    id: 27,
    dieId: 9,
    name:        "Basic Action Card",
    subtitle:    "Force Beam",
    cost:        3,
    type:        "Generic",
    affiliation: "None",
    rarity:      "Starter",
    ability:     "Deal 1 damage to each character.",
    "* ability": "Deal 1 extra damage to each character.",
    "** ability":  "Deal 1 extra damage to each player and each character.",
    global:       "",
    dieLimit:   3
  },
  {
    id: 28,
    dieId: 9,
    name:        "Basic Action Card",
    subtitle:    "Gearing Up",
    cost:        4,
    type:        "Generic",
    affiliation: "None",
    rarity:      "Starter",
    ability:     "Draw and roll two dice from your bag.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   3
  },
  {
    id: 29,
    dieId: 9,
    name:        "Basic Action Card",
    subtitle:    "Inner Rage",
    cost:        3,
    type:        "Generic",
    affiliation: "None",
    rarity:      "Starter",
    ability:     "Two of your target characters get +1A and +1D (until the end of the turn).",
    "* ability": "Those characters get an additional +1A and +1D.",
    "** ability":  "Those characters get an additional +1A and +1D.",
    global:       "",
    dieLimit:   3
  },
  {
    id: 30,
    dieId: 9,
    name:        "Basic Action Card",
    subtitle:    "Invulnerability",
    cost:        2,
    type:        "Generic",
    affiliation: "None",
    rarity:      "Starter",
    ability:     "Your attacking characters that are knocked out (this turn) return to the field.",
    "* ability": "",
    "** ability":  "",
    global:       "Pay [1 Bolt]. One target character gets +1A (until the end of the turn).",
    dieLimit:   3
  },
  {
    id: 31,
    dieId: 9,
    name:        "Basic Action Card",
    subtitle:    "Power Bolt",
    cost:        3,
    type:        "Generic",
    affiliation: "None",
    rarity:      "Starter",
    ability:     "Deal 2 damage to one target character or player.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   3
  },
  {
    id: 32,
    dieId: 9,
    name:        "Basic Action Card",
    subtitle:    "Smash!",
    cost:        3,
    type:        "Generic",
    affiliation: "None",
    rarity:      "Starter",
    ability:     "Knock out a target level 1 character.",
    "* ability": "",
    "** ability":  "Knock out a level 2 or lower character instead.",
    global:       "Pay [1 Fist].  Target blocked character deals no damage.",
    dieLimit:   3
  },
  {
    id: 33,
    dieId: 9,
    name:        "Basic Action Card",
    subtitle:    "Take Cover",
    cost:        3,
    type:        "Generic",
    affiliation: "None",
    rarity:      "Starter",
    ability:     "Your characters get +2D.",
    "* ability": "One character gets an extra +3D.",
    "** ability":  "One character gets an extra +3D.",
    global:       "Pay [1 Shield]to give one target character +1D (until the end of the turn).",
    dieLimit:   3
  },
  {
    id: 34,
    dieId: 9,
    name:        "Basic Action Card",
    subtitle:    "Thrown Car",
    cost:        4,
    type:        "Generic",
    affiliation: "None",
    rarity:      "Starter",
    ability:     "Two of your target characters get +1A.  While attacking, damage that those two characters deal in excess of the total defense of blocking characters is dealt to your opponent.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   3
  },
  {
    id: 35,
    dieId: 10,
    name:        "Angel",
    subtitle:    "High Ground",
    cost:        3,
    type:        "Shield",
    affiliation: "None",
    rarity:      "Common",
    ability:     "Angel cannot be blocked by a character with a lower level.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 36,
    dieId: 11,
    name:        "Black Widow",
    subtitle:    "Natural",
    cost:        2,
    type:        "Fist",
    affiliation: "Avengers",
    rarity:      "Common",
    ability:     "At the end of the attack step, spin each character assigned with Black Widow down 1 level (this happens before damage clears).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 37,
    dieId: 12,
    name:        "Colossus",
    subtitle:    "Unstoppable",
    cost:        6,
    type:        "Fist",
    affiliation: "X-Men",
    rarity:      "Common",
    ability:     "At the end of your turn, spin each of your Colossus in the field up one level.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 38,
    dieId: 13,
    name:        "Cyclops",
    subtitle:    "Slim",
    cost:        5,
    type:        "Bolt",
    affiliation: "X-Men",
    rarity:      "Common",
    ability:     "When Cyclops is blocked by more than one character, he deals damage equal to his full attack to each character blocking him (instead of having to split it).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 39,
    dieId: 14,
    name:        "Deadpool",
    subtitle:    "Assassin",
    cost:        4,
    type:        "Fist",
    affiliation: "None",
    rarity:      "Common",
    ability:     "When Deadpool attacks, you may assign an opposing character to block him.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 40,
    dieId: 15,
    name:        "Doctor Doom",
    subtitle:    "Reed Richard's Rival",
    cost:        5,
    type:        "Shield",
    affiliation: "Villains",
    rarity:      "Common",
    ability:     "While Doctor Doom is active, each non-Villain character gets -1A and -1D (no matter how many Doctor Doom dice you have fielded).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 41,
    dieId: 16,
    name:        "Doctor Octopus",
    subtitle:    "Megalomaniac",
    cost:        6,
    type:        "Shield",
    affiliation: "Villains",
    rarity:      "Common",
    ability:     "When Doctor Octopus assigns to attack, target an opposing character.  That character cannot block (this turn).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 42,
    dieId: 17,
    name:        "Doctor Strange",
    subtitle:    "Sorcerer Supreme",
    cost:        7,
    type:        "Mask",
    affiliation: "None",
    rarity:      "Common",
    ability:     "While Doctor Strange is active, you may purchase one action die for free during your main step (not one action die per Doctor Strange die).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 43,
    dieId: 18,
    name:        "Gambit",
    subtitle:    "Ace in the Hole",
    cost:        3,
    type:        "Mask",
    affiliation: "X-Men",
    rarity:      "Common",
    ability:     "When fielded, you may draw and roll one die (place it in your reserve pool).",
    "* ability": "Instead draw 2 dice, roll one of them and return the other to your bag.",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 44,
    dieId: 19,
    name:        "Ghost Rider",
    subtitle:    "Johnny Blaze",
    cost:        2,
    type:        "Bolt",
    affiliation: "None",
    rarity:      "Common",
    ability:     "(No special effects; just a low-cost die with good numbers.)",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 45,
    dieId: 20,
    name:        "Green Goblin",
    subtitle:    "Goblin-Lord",
    cost:        3,
    type:        "Bolt",
    affiliation: "Villains",
    rarity:      "Common",
    ability:     "While Green Goblin is active, your Sidekick characters get +1A and +1D (no matter how many Green Goblin dice you have fielded).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 46,
    dieId: 21,
    name:        "Hawkeye",
    subtitle:    "Longbow",
    cost:        4,
    type:        "Bolt",
    affiliation: "Avengers",
    rarity:      "Common",
    ability:     "When fielded, Hawkeye deals his attack value in damage to a target opposing character.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   3
  },
  {
    id: 47,
    dieId: 22,
    name:        "Loki",
    subtitle:    "Trickster",
    cost:        6,
    type:        "Mask",
    affiliation: "Villains",
    rarity:      "Common",
    ability:     "When fielded, capture an opposing die of equal or lower level (return it to your opponent's field at the end of the turn).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 48,
    dieId: 23,
    name:        "Magneto",
    subtitle:    "Former Comrade",
    cost:        5,
    type:        "Mask",
    affiliation: "Villains",
    rarity:      "Common",
    ability:     "Magneto gets +2A and +2D when engaged with an X-Men character.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 49,
    dieId: 24,
    name:        "Mr. Fantastic",
    subtitle:    "Brilliant Scientist",
    cost:        3,
    type:        "Mask",
    affiliation: "Fantastic Four",
    rarity:      "Common",
    ability:     "Mr. Fantastic gets +2A and +2D while blocking.",
    "* ability": "",
    "** ability":  "",
    global:      "Pay [1 Mask].  Target character must attack this turn.",
    dieLimit:   4
  },
  {
    id: 50,
    dieId: 25,
    name:        "Mystique",
    subtitle:    "Unknown",
    cost:        4,
    type:        "Mask",
    affiliation: "Villains",
    rarity:      "Common",
    ability:     "When Mystique is engaged, she copies the die stats and card abilities of one character that she is engaged with.",
    "* ability": "She also gains an extra +1A and +1D.",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 51,
    dieId: 26,
    name:        "Nick Fury",
    subtitle:    "Mr. Anger",
    cost:        2,
    type:        "Shield",
    affiliation: "None",
    rarity:      "Common",
    ability:     "While Nick Fury is active, you may field Avengers characters for free.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 52,
    dieId: 27,
    name:        "Nightcrawler",
    subtitle:    "Fuzzy Elf",
    cost:        5,
    type:        "Fist",
    affiliation: "None",
    rarity:      "Common",
    ability:     "Nightcrawler cannot be blocked by non-[Mask] characters.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 53,
    dieId: 28,
    name:        "Nova",
    subtitle:    "Quasar",
    cost:        5,
    type:        "Bolt",
    affiliation: "None",
    rarity:      "Common",
    ability:     "Each time Nova takes damage, you may draw one die and put it in your prep area.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 54,
    dieId: 29,
    name:        "Phoenix",
    subtitle:    "Ms. Psyche",
    cost:        6,
    type:        "Bolt",
    affiliation: "X-Men",
    rarity:      "Common",
    ability:     "When Phoenix is engaged, she gains +2A and +2D.",
    "* ability": "",
    "** ability":  "",
    global:       "Pay [1 Bolt].  Target character must attack.",
    dieLimit:   3
  },
  {
    id: 55,
    dieId: 30,
    name:        "Professor X",
    subtitle:    "Principal",
    cost:        6,
    type:        "Mask",
    affiliation: "X-Men",
    rarity:      "Common",
    ability:     "While Professor X is active, your opponent cannot reroll dice during the Roll and Reroll Step.  He or she can pay 2 life to prevent this effect for this turn.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   3
  },
  {
    id: 56,
    dieId: 31,
    name:        "Punisher",
    subtitle:    "McRook",
    cost:        4,
    type:        "Bolt",
    affiliation: "None",
    rarity:      "Common",
    ability:     "When Punisher assigns to attack, knock out one target opposing character.  Your opponent may prevent this effect by paying 2 life.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 57,
    dieId: 32,
    name:        "Rogue",
    subtitle:    "Anna Raven",
    cost:        4,
    type:        "Mask",
    affiliation: "X-Men",
    rarity:      "Common",
    ability:     "When fielded, you may capture an opposing die in the used pile (return it at the end of the turn).  Spin it to level 1. Rogue copies that die's stats.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 58,
    dieId: 33,
    name:        "Silver Surfer",
    subtitle:    "Silverado",
    cost:        6,
    type:        "Shield",
    affiliation: "None",
    rarity:      "Common",
    ability:     "At the start of the attack step, if your opponent has more life than you, Silver Surfer gets +2A and +2D.",
    "* ability": "",
    "** ability":  "",
    global:       "Once during your turn, pay [1 Shield] and take 2 damage to draw one die and place it in your prep area.",
    dieLimit:   4
  },
  {
    id: 59,
    dieId: 34,
    name:        "Thing",
    subtitle:    "Ever-Lovin' Blue-Eyed",
    cost:        6,
    type:        "Fist",
    affiliation: "Fantastic Four",
    rarity:      "Common",
    ability:     "At the start of the attack step, if your opponent has more fielded characters than you, Thing can't be blocked and takes no damage while blocking.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 60,
    dieId: 35,
    name:        "Venom",
    subtitle:    "Eddie Brock",
    cost:        6,
    type:        "Fist",
    affiliation: "Villains",
    rarity:      "Common",
    ability:     "Non-[Fist] characters can't block Venom.",
    "* ability": "",
    "** ability":  "",
    global:       "Pay [1 Fist] to spin an opponent's [Fist] character down 1 level.",
    dieLimit:   4
  },
  {
    id: 61,
    dieId: 36,
    name:        "War Machine",
    subtitle:    "Combat Comrade",
    cost:        5,
    type:        "Shield",
    affiliation: "None",
    rarity:      "Common",
    ability:     "War Machine gets +2A and +2D if you have Iron Man in the field.",
    "* ability": "",
    "** ability":  "",
    global:       "When one of your [Shield] characters damages your opponent in the attack step, pay [Shield] to gain 1 life.",
    dieLimit:   4
  },
  {
    id: 62,
    dieId: 37,
    name:        "Wolverine",
    subtitle:    "Wildboy",
    cost:        5,
    type:        "Fist",
    affiliation: "X-Men",
    rarity:      "Common",
    ability:     "When Wolverine attacks alone, you may spin one opponent's character down one level.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   3
  },
  {
    id: 63,
    dieId: 38,
    name:        "Mjolnir",
    subtitle:    "Fist of the Righteous",
    cost:        6,
    type:        "Bolt",
    affiliation: "None",
    rarity:      "Common",
    ability:     "Deal 6 damage to each villain.",
    "* ability": "",
    "** ability":  "Deal 8 damage to each villain instead.",
    global:      "Pay [2 Bolt] to deal 1 damage to a target character.",
    dieLimit:   3
  },
  {
    id: 64,
    dieId: 39,
    name:        "Vibranium Shield",
    subtitle:    "One of a Kind",
    cost:        4,
    type:        "Shield",
    affiliation: "None",
    rarity:      "Common",
    ability:     "At the start of your attack step, choose an energy type.  This turn, characters of that type take no damage.",
    "* ability": "",
    "** ability":  "",
    global:       "Pay [1 Shield] to prevent 1 damage to a character or player.",
    dieLimit:   4
  },
  {
    id: 65,
    dieId: 10,
    name:        "Angel",
    subtitle:    "Avenging Angel",
    cost:        3,
    type:        "Shield",
    affiliation: "None",
    rarity:      "Uncommon",
    ability:     "If Angel is blocked but is not knocked out, he deals 2 damage to the opposing player.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 66,
    dieId: 1,
    name:        "Beast",
    subtitle:    "Kreature",
    cost:        3,
    type:        "Mask",
    affiliation: "X-Men",
    rarity:      "Uncommon",
    ability:     "When Beast blocks, spin the blocked character down 1 level.  If it is already level 1, knock it out.",
    "* ability": "If the blocked character is knocked out by this, gain 2 life.",
    "** ability":  "",
    global:       "",
    dieLimit:   5
  },
  {
    id: 67,
    dieId: 2,
    name:        "Captain America",
    subtitle:    "Sentinel of Liberty",
    cost:        6,
    type:        "Shield",
    affiliation: "Avengers",
    rarity:      "Uncommon",
    ability:     "While Captain America is active, your Sidekick characters get +2A, and your opponent's Sidekick characters cost 1 extra energy to field.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   5
  },
  {
    id: 68,
    dieId: 12,
    name:        "Colossus",
    subtitle:    "Russian Bear",
    cost:        7,
    type:        "Fist",
    affiliation: "X-Men",
    rarity:      "Uncommon",
    ability:     "",
    "* ability": "If Colossus damaged your opponent, return Colossus to the prep area instead of the used pile.",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 69,
    dieId: 13,
    name:        "Cyclops",
    subtitle:    "If Looks Could Kill",
    cost:        7,
    type:        "Bolt",
    affiliation: "X-Men",
    rarity:      "Uncommon",
    ability:     "When Cyclops is assigned to attack, before blockers are assigned, he deals his attack in damage to each opposing character.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   2
  },
  {
    id: 70,
    dieId: 14,
    name:        "Deadpool",
    subtitle:    "Jack",
    cost:        5,
    type:        "Fist",
    affiliation: "None",
    rarity:      "Uncommon",
    ability:     "When Deadpool attacks, you may assign an opposing character to block him.  At the end of the turn, knock out that character.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 71,
    dieId: 15,
    name:        "Doctor Doom",
    subtitle:    "Nemesis",
    cost:        6,
    type:        "Shield",
    affiliation: "Villains",
    rarity:      "Uncommon",
    ability:     "Doctor Doom can only be blocked by Villain and Sidekick characters.",
    "* ability": "",
    "** ability":  "",
    global:       "If you have a Villain fielded, pay [1 Shield] to give a target character -1A and -1D (knock out those with zero defense).",
    dieLimit:   4
  },
  {
    id: 72,
    dieId: 16,
    name:        "Doctor Octopus",
    subtitle:    "Fully Armed",
    cost:        6,
    type:        "Shield",
    affiliation: "Villains",
    rarity:      "Uncommon",
    ability:     "When blocked, any damage that Doctor Octopus does in excess of his blocking characters' total defense is dealt to your opponent.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 73,
    dieId: 17,
    name:        "Doctor Strange",
    subtitle:    "Master of the Mystic Arts",
    cost:        6,
    type:        "Mask",
    affiliation: "None",
    rarity:      "Uncommon",
    ability:     "While Doctor Strange is active, each time you use an action he deals 2 damage to a character or opponent (no matter how many dice are fielded).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 74,
    dieId: 18,
    name:        "Gambit",
    subtitle:    "Le Diable Blanc",
    cost:        5,
    type:        "Mask",
    affiliation: "X-Men",
    rarity:      "Uncommon",
    ability:     "When fielded, draw and roll 2 dice.  Field characters rolled on those dice for free; place the rest in your used pile.",
    "* ability": "Instead draw 3 dice, choose two to roll and return the other to your bag.",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 75,
    dieId: 19,
    name:        "Ghost Rider",
    subtitle:    "Spirit of Vengeance",
    cost:        4,
    type:        "Bolt",
    affiliation: "None",
    rarity:      "Uncommon",
    ability:     "If Ghost Rider is knocked out while engaged, draw one die from your bag and place it in your prep area.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 76,
    dieId: 21,
    name:        "Hawkeye",
    subtitle:    "Br'er Hawkeye",
    cost:        3,
    type:        "Bolt",
    affiliation: "Avengers",
    rarity:      "Uncommon",
    ability:     "Spin characters damaged by Hawkeye to level 1.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 78,
    dieId: 4,
    name:        "Human Torch",
    subtitle:    "Johnny Storm",
    cost:        4,
    type:        "Bolt",
    affiliation: "Fantastic Four",
    rarity:      "Uncommon",
    ability:     "While Human Torch is active, each time you field a character, Human Torch deals 1 damage to your opponent and one to a target character (not 1 damage per Human Torch die).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   5
  },
  {
    id: 77,
    dieId: 3,
    name:        "Hulk",
    subtitle:    "Green Goliath",
    cost:        6,
    type:        "Fist",
    affiliation: "Avengers",
    rarity:      "Uncommon",
    ability:     "While Hulk is active, whenever either you or Hulk takes damage, Hulk deals 2 damage to each opposing character (no matter how many Hulks are fielded).",
    "* ability": "He deals 3 damage instead.",
    "** ability":  "",
    global:       "",
    dieLimit:   5
  },
  {
    id: 79,
    dieId: 5,
    name:        "Iron Man",
    subtitle:    "Billionaire",
    cost:        6,
    type:        "Shield",
    affiliation: "Avengers",
    rarity:      "Uncommon",
    ability:     "Iron Man takes no damage from non-[Shield] characters.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   5
  },
  {
    id: 80,
    dieId: 22,
    name:        "Loki",
    subtitle:    "Illusionist",
    cost:        7,
    type:        "Mask",
    affiliation: "Villains",
    rarity:      "Uncommon",
    ability:     "When fielded, take control of an opposing character.  At the end of the turn, knock out that character (place it in your opponent's prep area); it deals damage equal to it's attack to your opponent.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   3
  },
  {
    id: 81,
    dieId: 23,
    name:        "Magneto",
    subtitle:    "Holocaust Survivor",
    cost:        6,
    type:        "Mask",
    affiliation: "Villains",
    rarity:      "Uncommon",
    ability:     "While Magneto is active, you may pay 2 energy to spin a Villain up one level.",
    "* ability": "",
    "** ability":  "",
    global:       "Pay [1 Mask] to reroll a Villain die.",
    dieLimit:   4
  },
  {
    id: 82,
    dieId: 25,
    name:        "Mystique",
    subtitle:    "Shapeshifter",
    cost:        6,
    type:        "Mask",
    affiliation: "Villains",
    rarity:      "Uncommon",
    ability:     "When fielded, choose an opponent's character card.  Mystique copies that card (except purchase cost and the die faces) until the next Mystique is fielded.",
    "* ability": "She also copies the die faces (matching level for level).",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 83,
    dieId: 26,
    name:        "Nick Fury",
    subtitle:    "WWII Veteran",
    cost:        2,
    type:        "Shield",
    affiliation: "None",
    rarity:      "Uncommon",
    ability:     "While Nick Fury is active, your Avengers characters get +1A and +1D.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 84,
    dieId: 27,
    name:        "Nightcrawler",
    subtitle:    "Abandoned",
    cost:        4,
    type:        "Fist",
    affiliation: "None",
    rarity:      "Uncommon",
    ability:     "At the end of the attack step, knock out one character that blocked Nightcrawler.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 85,
    dieId: 28,
    name:        "Nova",
    subtitle:    "Bucket Head",
    cost:        6,
    type:        "Bolt",
    affiliation: "None",
    rarity:      "Uncommon",
    ability:     "The first time Nova takes damage each turn, you may redirect that damage to one target character.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   3
  },
  {
    id: 86,
    dieId: 29,
    name:        "Phoenix",
    subtitle:    "Redd",
    cost:        7,
    type:        "Bolt",
    affiliation: "X-Men",
    rarity:      "Uncommon",
    ability:     "When Phoenix is engaged, you may spend [2 Bolt] to deal 4 damage to target character or opponent.",
    "* ability": "",
    "** ability":  "",
    global:       "Pay [1 Bolt].  Target character must attack.",
    dieLimit:   3
  },
  {
    id: 87,
    dieId: 30,
    name:        "Professor X",
    subtitle:    "Powerful Telepath",
    cost:        5,
    type:        "Mask",
    affiliation: "X-Men",
    rarity:      "Uncommon",
    ability:     "While Professor X is active, your opponent cannot use actions or global abilities.  He or she can pay 2 life to prevent this effect for the rest of the turn.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 88,
    dieId: 31,
    name:        "Punisher",
    subtitle:    "Vigilante",
    cost:        5,
    type:        "Bolt",
    affiliation: "None",
    rarity:      "Uncommon",
    ability:     "When Punisher assigns to attack, search your bag for a Punisher die and put it into your prep area.  Your opponent can prevent this by paying 3 life.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   3
  },
  {
    id: 89,
    dieId: 32,
    name:        "Rogue",
    subtitle:    "Anna Marie",
    cost:        5,
    type:        "Mask",
    affiliation: "X-Men",
    rarity:      "Uncommon",
    ability:     "When fielded, capture an opposing action die from the used pile or reserve pool.  When Rogue attacks, you may use that action for free (with no bursts).  Return it to the used pile after the attack step.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 90,
    dieId: 33,
    name:        "Silver Surfer",
    subtitle:    "Sentinel",
    cost:        6,
    type:        "Shield",
    affiliation: "None",
    rarity:      "Uncommon",
    ability:     "While Silver Surfer is active, if your opponent has more life than you, draw one extra die each Clear and Draw Step.",
    "* ability": "",
    "** ability":  "",
    global:       "Once during your turn, pay [1 Shield] and take 2 damage to draw one die and place it in your prep area.",
    dieLimit:   4
  },
  {
    id: 91,
    dieId: 6,
    name:        "Spider-Man",
    subtitle:    "Wall-Crawler",
    cost:        4,
    type:        "Fist",
    affiliation: "None",
    rarity:      "Uncommon",
    ability:     "If Spider-Man attacks and is not blocked, you may pay [2 Fist] to change your opponent's life to 10 (before damage is dealt).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   5
  },
  {
    id: 92,
    dieId: 7,
    name:        "Storm",
    subtitle:    "Wind-Rider",
    cost:        5,
    type:        "Mask",
    affiliation: "X-Men",
    rarity:      "Uncommon",
    ability:     "When fielded, reroll up to 2 opposing characters.  Each die that does not roll a character goes to your opponent's used pile. Storm deals 2 damage to your opponent for each die moved.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   5
  },
  {
    id: 93,
    dieId: 34,
    name:        "Thing",
    subtitle:    "Grim Ben",
    cost:        5,
    type:        "Fist",
    affiliation: "Fantastic Four",
    rarity:      "Uncommon",
    ability:     "At the start of the attack step, if your opponent has more fielded characters than you, Thing gets +3A and +3D (until the end of the turn).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 94,
    dieId: 8,
    name:        "Thor",
    subtitle:    "God of Thunder",
    cost:        6,
    type:        "Bolt",
    affiliation: "Avengers",
    rarity:      "Uncommon",
    ability:     "At the start of the attack step, Thor gets +4A and +4D for each opposing [Fist] character in the field (until the end of the turn).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   5
  },
  {
    id: 95,
    dieId: 35,
    name:        "Venom",
    subtitle:    "Mac Gargan",
    cost:        5,
    type:        "Fist",
    affiliation: "Villains",
    rarity:      "Uncommon",
    ability:     "If Venom blocks and knocks out a non-[Fist] character, he deals 2 damage to your opponent and you gain 1 life.",
    "* ability": "",
    "** ability":  "",
    global:       "Pay [1 Fist] to spin an opponent's [Fist] character down 1 level.",
    dieLimit:   4
  },
  {
    id: 96,
    dieId: 36,
    name:        "War Machine",
    subtitle:    "Parnell Jacobs",
    cost:        5,
    type:        "Shield",
    affiliation: "None",
    rarity:      "Uncommon",
    ability:     "War Machine can't be blocked if you have Iron Man fielded.",
    "* ability": "",
    "** ability":  "",
    global:       "When one of your [Shield] characters damages your opponent in the attack step, pay [1 Shield] to gain 1 life.",
    dieLimit:   4
  },
  {
    id: 97,
    dieId: 38,
    name:        "Mjolnir",
    subtitle:    "Forged by Odin",
    cost:        6,
    type:        "Bolt",
    affiliation: "None",
    rarity:      "Uncommon",
    ability:     "Deal 5 damage to target character.",
    "* ability": "Deal an extra 1 damage.",
    "** ability":  "Deal an extra 3 damage.",
    global:       "Pay [2 Bolt] to deal 1 damage to a target character.",
    dieLimit:   3
  },
  {
    id: 98,
    dieId: 39,
    name:        "Vibranium Shield",
    subtitle:    "Irreplaceable",
    cost:        6,
    type:        "Shield",
    affiliation: "None",
    rarity:      "Uncommon",
    ability:     "Place this die touching an opposing character.  Opposing characters that match that character's type cannot attack or block until the end of your opponent's next turn.  Then place this die in the used pile.",
    "* ability": "",
    "** ability":  "",
    global:       "Pay [1 Shield] to prevent 1 damage to a character or player.",
    dieLimit:   4
  },
  {
    id: 99,
    dieId: 10,
    name:        "Angel",
    subtitle:    "Soaring",
    cost:        2,
    type:        "Shield",
    affiliation: "None",
    rarity:      "Rare",
    ability:     "If you used an action this turn, Angel cannot be blocked.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 100,
    dieId: 11,
    name:        "Black Widow",
    subtitle:    "Killer Instinct",
    cost:        2,
    type:        "Fist",
    affiliation: "Avengers",
    rarity:      "Rare",
    ability:     "When fielded, spin one target opponent's character down to level 1.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 101,
    dieId: 12,
    name:        "Colossus",
    subtitle:    "Piotr Rasputin",
    cost:        7,
    type:        "Fist",
    affiliation: "X-Men",
    rarity:      "Rare",
    ability:     "While Colossus is active, at the end of your turn, each of your characters of level 2 or higher deals 2 damage to your opponent (not 2 damage per Colossus die).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 102,
    dieId: 13,
    name:        "Cyclops",
    subtitle:    "Scott Summers",
    cost:        7,
    type:        "Bolt",
    affiliation: "X-Men",
    rarity:      "Rare",
    ability:     "If Cyclops is blocked, you may have him deal damage to your opponent instead of his blocker(s).  If you do so, he goes to your used pile during cleanup.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 103,
    dieId: 14,
    name:        "Deadpool",
    subtitle:    "Chiyonosake",
    cost:        5,
    type:        "Fist",
    affiliation: "None",
    rarity:      "Rare",
    ability:     "When Deadpool attacks, you may assign an opposing character to block him.  If he knocks out that character, he deals 2 damage to each opposing character.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 104,
    dieId: 15,
    name:        "Doctor Doom",
    subtitle:    "Victor",
    cost:        6,
    type:        "Shield",
    affiliation: "Villains",
    rarity:      "Rare",
    ability:     "When fielded, each player must knock out all but one of his or her non-Villain characters (place those knocked out dice in that player's prep area).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 105,
    dieId: 16,
    name:        "Doctor Octopus",
    subtitle:    "Mad Scientist",
    cost:        6,
    type:        "Shield",
    affiliation: "Villains",
    rarity:      "Rare",
    ability:     "When Doctor Octopus is blocked by more than one character, he deals his full attack value in damage to each character blocking him (instead of having to split it).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 106,
    dieId: 17,
    name:        "Doctor Strange",
    subtitle:    "Probably a Charlatan",
    cost:        7,
    type:        "Mask",
    affiliation: "None",
    rarity:      "Rare",
    ability:     "When fielded, search your bag for an action die and roll it (place it into your reserve pool).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 107,
    dieId: 18,
    name:        "Gambit",
    subtitle:    "Cardsharp",
    cost:        5,
    type:        "Mask",
    affiliation: "X-Men",
    rarity:      "Rare",
    ability:     "When fielded, you may draw and roll one die.  If you roll a character side, that character deals damage equal to its attack to your opponent and goes to your used pile (otherwise, the die goes to your reserve pool).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 108,
    dieId: 19,
    name:        "Ghost Rider",
    subtitle:    "Brimstone Biker",
    cost:        4,
    type:        "Bolt",
    affiliation: "None",
    rarity:      "Rare",
    ability:     "When fielded, select a die from your used pile and place it into your prep area (you cannot select a die that paid to field this die).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 109,
    dieId: 20,
    name:        "Green Goblin",
    subtitle:    "Norman Osborn",
    cost:        4,
    type:        "Bolt",
    affiliation: "Villains",
    rarity:      "Rare",
    ability:     "When fielded, you may roll up to 2 Sidekick dice from your used pile (you cannot roll dice that paid to field this dice; place rolled dice in your reserve pool).",
    "* ability": "",
    "** ability":  "",
    global:       "Pay [1 Bolt] and knock out one of your sidekick characters to deal 2 damage to target character.",
    dieLimit:   4
  },
  {
    id: 110,
    dieId: 21,
    name:        "Hawkeye",
    subtitle:    "Robin Hood",
    cost:        3,
    type:        "Bolt",
    affiliation: "Avengers",
    rarity:      "Rare",
    ability:     "When assigning damage in an attack step, Hawkeye assigns and resolves his damage before opposing characters.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 111,
    dieId: 22,
    name:        "Loki",
    subtitle:    "Gem-Keeper",
    cost:        5,
    type:        "Mask",
    affiliation: "Villains",
    rarity:      "Rare",
    ability:     "When fielded, choose an opponent's character card, canceling all previous choices.  Your opponent cannot field that character while Loki is active.  This effect lasts until you field another Loki.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 112,
    dieId: 23,
    name:        "Magneto",
    subtitle:    "Sonderkommando",
    cost:        6,
    type:        "Mask",
    affiliation: "Villains",
    rarity:      "Rare",
    ability:     "While Magneto is active, your other Villain characters get +2A and +2D (no matter how many Magneto dice you have fielded).",
    "* ability": "",
    "** ability":  "",
    global:       "Pay [1 Mask] to reroll a Villain die.",
    dieLimit:   4
  },
  {
    id: 113,
    dieId: 24,
    name:        "Mr. Fantastic",
    subtitle:    "The Invincible Man",
    cost:        5,
    type:        "Mask",
    affiliation: "Fantastic Four",
    rarity:      "Rare",
    ability:     "While blocking, you may redirect up to 2 damage from Mr. Fantastic to the character he blocks.",
    "* ability": "",
    "** ability":  "",
    global:       "Pay [1 Mask].  Target character must attack this turn.",
    dieLimit:   3
  },
  {
    id: 114,
    dieId: 25,
    name:        "Mystique",
    subtitle:    "Could Be Anyone",
    cost:        5,
    type:        "Mask",
    affiliation: "Villains",
    rarity:      "Rare",
    ability:     "At beginning of your turn, choose an opposing fielded character. Each of your Mystique dice copies the stats on that character's die until your next turn.",
    "* ability": "She also gains an extra +1A and +1D.",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 115,
    dieId: 26,
    name:        "Nick Fury",
    subtitle:    "Patch",
    cost:        4,
    type:        "Shield",
    affiliation: "None",
    rarity:      "Rare",
    ability:     "While Nick Fury is active, your unblocked Avengers characters deal damage to your opponent twice.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   2
  },
  {
    id: 116,
    dieId: 27,
    name:        "Nightcrawler",
    subtitle:    "Circus Freak",
    cost:        4,
    type:        "Fist",
    affiliation: "None",
    rarity:      "Rare",
    ability:     "After assigning blockers, knock out one character blocking Nightcrawler (before assigning damage).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 117,
    dieId: 28,
    name:        "Nova",
    subtitle:    "The Human Rocket",
    cost:        5,
    type:        "Bolt",
    affiliation: "None",
    rarity:      "Rare",
    ability:     "Whenever Nova takes damage in an attack step, he deals 2 damage to your opponent.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 118,
    dieId: 29,
    name:        "Phoenix",
    subtitle:    "Jeannie",
    cost:        7,
    type:        "Bolt",
    affiliation: "X-Men",
    rarity:      "Rare",
    ability:     "At the end of the attack step, each character still engaged with Phoenix deals damage equal to its attack to your opponent.  Knock out those characters.",
    "* ability": "",
    "** ability":  "",
    global:       "Pay [1 Bolt].  Target character must attack.",
    dieLimit:   3
  },
  {
    id: 119,
    dieId: 30,
    name:        "Professor X",
    subtitle:    "Charles Francis Xavier",
    cost:        6,
    type:        "Mask",
    affiliation: "X-Men",
    rarity:      "Rare",
    ability:     "While Professor X is active, your opponent cannot field characters.  He or she can pay 2 life to prevent this effect for the rest of this turn.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 120,
    dieId: 31,
    name:        "Punisher",
    subtitle:    "Big Nothing",
    cost:        6,
    type:        "Bolt",
    affiliation: "None",
    rarity:      "Rare",
    ability:     "When Punisher assigns to attack, he deals 2 damage to each opposing character.  Your opponent can prevent this effect by paying 4 life.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 121,
    dieId: 32,
    name:        "Rogue",
    subtitle:    "Can't Touch This",
    cost:        6,
    type:        "Mask",
    affiliation: "X-Men",
    rarity:      "Rare",
    ability:     "When fielded, capture an opposing fielded character (until the end of the turn).  Rogue copies that character's stats and abilities.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 122,
    dieId: 33,
    name:        "Silver Surfer",
    subtitle:    "Sky-Rider",
    cost:        7,
    type:        "Shield",
    affiliation: "None",
    rarity:      "Rare",
    ability:     "At the start of the attack step, if your opponent has more life than you, double Silver Surfer's attack and defense.",
    "* ability": "",
    "** ability":  "",
    global:       "Once during your turn, pay [1 Shield] and take 2 dmage to draw a die and place it in your prep area.",
    dieLimit:   4
  },
  {
    id: 123,
    dieId: 34,
    name:        "Thing",
    subtitle:    "Idol of Millions",
    cost:        7,
    type:        "Fist",
    affiliation: "Fantastic Four",
    rarity:      "Rare",
    ability:     "When fielded, if your opponent has more fielded characters than you, draw and roll 3 dice (place them in your reserve pool).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 124,
    dieId: 35,
    name:        "Venom",
    subtitle:    "Angelo Fortunato",
    cost:        6,
    type:        "Fist",
    affiliation: "Villains",
    rarity:      "Rare",
    ability:     "While Venom is active, your opponent's non-[Fist] characters get -2A and -2D.",
    "* ability": "Your [Fist] characters get +1A and +1D.",
    "** ability":  "",
    global:       "Pay [1 Fist] to spin an opponent's [Fist] character down 1 level.",
    dieLimit:   4
  },
  {
    id: 125,
    dieId: 36,
    name:        "War Machine",
    subtitle:    "James Rhodes",
    cost:        5,
    type:        "Shield",
    affiliation: "None",
    rarity:      "Rare",
    ability:     "When fielded, if you have Iron Man fielded, knock out an opponent's character.",
    "* ability": "",
    "** ability":  "",
    global:      "When one of your [Shield] characters damages your opponent in the attack step, pay [1 Shield] to gain 1 life.",
    dieLimit:   4
  },
  {
    id: 126,
    dieId: 37,
    name:        "Wolverine",
    subtitle:    "Formerly Weapon Ten",
    cost:        4,
    type:        "Fist",
    affiliation: "X-Men",
    rarity:      "Rare",
    ability:     "When Wolverine attacks alone, he gains +4A and +4D.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 127,
    dieId: 38,
    name:        "Mjolnir",
    subtitle:    "Thor's Hammer",
    cost:        4,
    type:        "Bolt",
    affiliation: "None",
    rarity:      "Rare",
    ability:     "Deal 4 damage to all characters other than Thor (yours and your opponent's).",
    "* ability": "Deal 5 instead.",
    "** ability":  "",
    global:       "Pay [2 Bolt] to deal one damage to a target character.",
    dieLimit:   3
  },
  {
    id: 128,
    dieId: 39,
    name:        "Vibranium Shield",
    subtitle:    "Cap's Protection",
    cost:        5,
    type:        "Shield",
    affiliation: "None",
    rarity:      "Rare",
    ability:     "Place this die touching your target character.  It does not go to your used pile.  You may place this die in the used pile at any time to prevent all damage to the character for the rest of the turn.",
    "* ability": "",
    "** ability":  "",
    global:       "Pay [1 Shield] to prevent 1 damage to a character or player.",
    dieLimit:   4
  },
  {
    id: 129,
    dieId: 11,
    name:        "Black Widow",
    subtitle:    "Tsarina",
    cost:        2,
    type:        "Fist",
    affiliation: "Avengers",
    rarity:      "Super-Rare",
    ability:     "When Black Widow attacks, she deals 2 damage to your opponent. Your opponent can prevent this by spinning one of his or her characters down one level.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 130,
    dieId: 20,
    name:        "Green Goblin",
    subtitle:    "\"Gobby\"",
    cost:        3,
    type:        "Bolt",
    affiliation: "Villains",
    rarity:      "Super-Rare",
    ability:     "When fielded, Green Goblin deals 1 damage to your opponent for each Sidekick in the field (count your Sidekicks only).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 131,
    dieId: 24,
    name:        "Mr. Fantastic",
    subtitle:    "Elastic",
    cost:        4,
    type:        "Mask",
    affiliation: "Fantastic Four",
    rarity:      "Super-Rare",
    ability:     "You may spin Mr. Fantastic down 1 level to allow him to block an additional character (or 2 levels to block two additional characters).",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   4
  },
  {
    id: 132,
    dieId: 37,
    name:        "Wolverine",
    subtitle:    "Canucklehead",
    cost:        6,
    type:        "Fist",
    affiliation: "X-Men",
    rarity:      "Super-Rare",
    ability:     "When Wolverine attacks alone, he cannot be blocked.",
    "* ability": "",
    "** ability":  "",
    global:       "",
    dieLimit:   3
  }
];

var avengersVsXmenDieData = [
  {
    id: 1,
    name: "Beast",
    faces: [ "[1 Mask]", "[2 Mask]", "[2 Mask]", "[0/1/2/*]", "[0/2/3/-]", "[1/2/4/-]" ]
  },
  {
    id: 2,
    name: "Captain America",
    faces: [ "[1 Shield]", "[2 Shield]", "[2 Shield]", "[1/3/3/-]", "[2/5/4/-]", "[2/5/5/-]" ]
  },
  {
    id: 3,
    name: "Hulk",
    faces: [ "[1 Fist]", "[2 Fist]", "[2 Fist]", "[1/6/5/*]", "[2/7/7/*]", "[3/8/8/-]" ]
  },
  {
    id: 4,
    name: "Human Torch",
    faces: [ "[1 Bolt]", "[2 Bolt]", "[2 Bolt]", "[0/2/2/-]", "[1/3/3/-]", "[2/4/4/-]" ]
  },
  {
    id: 5,
    name: "Iron Man",
    faces: [ "[1 Shield]", "[2 Shield]", "[2 Shield]", "[1/3/5/-]", "[1/4/6/-]", "[2/5/7/*]" ]
  },
  {
    id: 6,
    name: "Spider-Man",
    faces: [ "[1 Fist]", "[2 Fist]", "[2 Fist]", "[0/3/3/-]", "[1/4/4/-]", "[1/5/5/-]" ]
  },
  {
    id: 7,
    name: "Storm",
    faces: [ "[1 Mask]", "[2 Mask]", "[2 Mask]", "[0/2/1/-]", "[1/2/2/-]", "[1/3/2/-]" ]
  },
  {
    id: 8,
    name: "Thor",
    faces: [ "[1 Bolt]", "[2 Bolt]", "[2 Bolt]", "[1/5/6/-]", "[2/6/8/-]", "[3/8/8/-]" ]
  },
  {
    id: 9,
    name: "Basic Action Card",
    faces: [ "[2 Generic]", "[2 Generic]", "[2 Generic]", "[-/-/-/-]", "[-/-/-/*]", "[-/-/-/**]" ]
  },
  {
    id: 10,
    name: "Angel",
    faces: [ "[1 Shield]", "[2 Shield]", "[2 Shield]", "[0/2/3/-]", "[1/3/3/-]", "[1/3/4/-]" ]
  },
  {
    id: 11,
    name: "Black Widow",
    faces: [ "[1 Fist]", "[2 Fist]", "[2 Fist]", "[0/2/1/-]", "[0/2/2/-]", "[1/3/3/-]" ]
  },
  {
    id: 12,
    name: "Colossus",
    faces: [ "[1 Fist]", "[2 Fist]", "[2 Fist]", "[1/4/4/-]", "[1/6/5/*]", "[2/8/7/*]" ]
  },
  {
    id: 13,
    name: "Cyclops",
    faces: [ "[1 Bolt]", "[2 Bolt]", "[2 Bolt]", "[1/4/2/-]", "[1/5/3/-]", "[1/6/4/-]" ]
  },
  {
    id: 14,
    name: "Deadpool",
    faces: [ "[1 Fist]", "[2 Fist]", "[2 Fist]", "[0/2/4/-]", "[0/2/5/-]", "[1/3/7/-]" ]
  },
  {
    id: 15,
    name: "Doctor Doom",
    faces: [ "[1 Shield]", "[2 Shield]", "[2 Shield]", "[1/3/6/-]", "[2/4/7/-]", "[3/5/8/-]" ]
  },
  {
    id: 16,
    name: "Doctor Octopus",
    faces: [ "[1 Shield]", "[2 Shield]", "[2 Shield]", "[1/4/4/-]", "[2/4/8/-]", "[3/8/8/-]" ]
  },
  {
    id: 17,
    name: "Doctor Strange",
    faces: [ "[1 Mask]", "[2 Mask]", "[2 Mask]", "[1/4/6/-]", "[2/5/8/-]", "[3/8/9/-]" ]
  },
  {
    id: 18,
    name: "Gambit",
    faces: [ "[1 Mask]", "[2 Mask]", "[2 Mask]", "[1/1/1/*]", "[1/2/2/*]", "[2/4/4/-]" ]
  },
  {
    id: 19,
    name: "Ghost Rider",
    faces: [ "[1 Bolt]", "[2 Bolt]", "[2 Bolt]", "[1/2/3/-]", "[2/3/4/-]", "[3/5/5/-]" ]
  },
  {
    id: 20,
    name: "Green Goblin",
    faces: [ "[1 Bolt]", "[2 Bolt]", "[2 Bolt]", "[0/2/2/-]", "[1/3/3/-]", "[1/5/5/-]" ]
  },
  {
    id: 21,
    name: "Hawkeye",
    faces: [ "[1 Bolt]", "[2 Bolt]", "[2 Bolt]", "[0/3/1/-]", "[0/4/1/-]", "[1/4/2/-]" ]
  },
  {
    id: 22,
    name: "Loki",
    faces: [ "[1 Mask]", "[2 Mask]", "[2 Mask]", "[1/1/5/-]", "[1/1/7/-]", "[2/2/8/-]" ]
  },
  {
    id: 23,
    name: "Magneto",
    faces: [ "[1 Mask]", "[2 Mask]", "[2 Mask]", "[1/4/4/-]", "[2/5/7/-]", "[3/6/8/-]" ]
  },
  {
    id: 24,
    name: "Mr. Fantastic",
    faces: [ "[1 Mask]", "[2 Mask]", "[2 Mask]", "[1/1/5/-]", "[2/2/6/-]", "[2/2/7/-]" ]
  },
  {
    id: 25,
    name: "Mystique",
    faces: [ "[1 Mask]", "[2 Mask]", "[2 Mask]", "[1/1/1/-]", "[0/1/1/-]", "[2/1/1/*]" ]
  },
  {
    id: 26,
    name: "Nick Fury",
    faces: [ "[1 Shield]", "[2 Shield]", "[2 Shield]", "[0/1/3/-]", "[1/2/4/-]", "[1/2/5/-]" ]
  },
  {
    id: 27,
    name: "Nightcrawler",
    faces: [ "[1 Fist]", "[2 Fist]", "[2 Fist]", "[1/2/4/-]", "[1/3/6/-]", "[2/5/6/-]" ]
  },
  {
    id: 28,
    name: "Nova",
    faces: [ "[1 Bolt]", "[2 Bolt]", "[2 Bolt]", "[1/4/4/-]", "[2/5/6/-]", "[2/7/7/-]" ]
  },
  {
    id: 29,
    name: "Phoenix",
    faces: [ "[1 Bolt]", "[2 Bolt]", "[2 Bolt]", "[1/5/5/-]", "[2/7/7/-]", "[3/8/8/-]" ]
  },
  {
    id: 30,
    name: "Professor X",
    faces: [ "[1 Mask]", "[2 Mask]", "[2 Mask]", "[1/1/5/-]", "[2/1/7/-]", "[3/1/9/-]" ]
  },
  {
    id: 31,
    name: "Punisher",
    faces: [ "[1 Bolt]", "[2 Bolt]", "[2 Bolt]", "[1/4/1/-]", "[1/5/2/-]", "[2/6/3/-]" ]
  },
  {
    id: 32,
    name: "Rogue",
    faces: [ "[1 Mask]", "[2 Mask]", "[2 Mask]", "[1/2/3/-]", "[2/4/5/-]", "[2/5/6/-]" ]
  },
  {
    id: 33,
    name: "Silver Surfer",
    faces: [ "[1 Shield]", "[2 Shield]", "[2 Shield]", "[1/5/5/-]", "[2/7/5/-]", "[3/8/7/-]" ]
  },
  {
    id: 34,
    name: "Thing",
    faces: [ "[1 Fist]", "[2 Fist]", "[2 Fist]", "[1/3/3/-]", "[2/5/5/-]", "[3/8/6/-]" ]
  },
  {
    id: 35,
    name: "Venom",
    faces: [ "[1 Fist]", "[2 Fist]", "[2 Fist]", "[1/4/4/-]", "[1/5/5/*]", "[2/6/6/*]" ]
  },
  {
    id: 36,
    name: "War Machine",
    faces: [ "[1 Shield]", "[2 Shield]", "[2 Shield]", "[1/3/4/-]", "[1/4/5/-]", "[2/5/6/-]" ]
  },
  {
    id: 37,
    name: "Wolverine",
    faces: [ "[1 Fist]", "[2 Fist]", "[2 Fist]", "[1/5/2/*]", "[2/6/3/*]", "[3/8/4/-]" ]
  },
  {
    id: 38,
    name: "Mjolnir",
    faces: [ "[1 Bolt]", "[2 Bolt]", "[2 Bolt]", "[-/-/-/-]", "[-/-/-/*]", "[-/-/-/**]" ]
  },
  {
    id: 39,
    name: "Vibranium Shield",
    faces: [ "[1 Shield]", "[2 Shield]", "[2 Shield]", "[-/-/-/-]", "[-/-/-/*]", "[-/-/-/**]" ]
  }
];